import type { Metadata } from "next";

import "./globals.css";
import { ThemeProvider } from "./provider";



export const metadata: Metadata = {
  title: "Rehneet Singh",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/heroImg.jpg" sizes="any" />
      </head>
      <body>
      <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
        {children}
        </ThemeProvider></body>
    </html>
  );
}
